BUCKET_NAME = 'wagon-data-893-dimarco2'
BUCKET_TRAIN_DATA_PATH = 'data/train_1k.csv'
BUCKET_TEST_DATA_PATH = 'data/test.csv'
MODEL_NAME = 'taxifare'
MODEL_VERSION = 'v1'
STORAGE_LOCATION = 'models/simpletaxifare/model.joblib'
